VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IBinaryConverter"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit


Public Function GetBinary(value As Variant, Optional prefix As String = "0x", Optional Profile As BinaryProfile = Nothing) As String
  
End Function

Public Sub ToBinary(ByRef binaryOut As String, value As Variant, Optional prefix As String = "0x", Optional Profile As BinaryProfile = Nothing)

End Sub

Public Sub AppendBinary(ByRef binaryOut As IStringBuilder, value As Variant, Optional prefix As String = "0x", Optional Profile As BinaryProfile = Nothing)

End Sub


