VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IFieldConverterSetup"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

' A helper class to let us pretend we have object constructors.

' You would never do this in a language that supported object constructors... _
  but VBA doesn't, so....
  
Public Sub Setup(formatter As IFormatRules)

End Sub



